image: maven:3.9-eclipse-temurin-17-alpine

services:
  - name: postgres:15-alpine
    alias: db_service

variables:
  POSTGRES_DB: ear2025zs_25
  POSTGRES_USER: ear2025zs_25
  POSTGRES_PASSWORD: $DB_PASSWORD 
  POSTGRES_HOST_AUTH_METHOD: trust

  SPRING_DATASOURCE_URL: jdbc:postgresql://db_service:5432/ear2025zs_25
  SPRING_DATASOURCE_USERNAME: ear2025zs_25
  SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD
  
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_SQL_INIT_MODE: always
  
  MAVEN_OPTS: "-Dmaven.test.skip=true"

stages:
  - test

run_postman_tests:
  stage: test
  script:
    - echo "Installing Newman..."
    - apk add --no-cache nodejs npm curl
    - npm install -g newman

    - echo "Building application..."
    - mvn clean package

    - echo "Starting Spring Boot..."
    - java -jar target/*.jar &

    - |
      echo "Waiting for server to start..."
      for i in {1..40}; do
        if curl -s http://localhost:8080/api/products > /dev/null; then
          echo "Server is UP and ready!"
          break
        fi
        echo "Waiting for server... ($i/40)"
        sleep 5
      done

    - echo "Running Postman Collections..."


    - newman run "postman/Admin_test.json" --env-var "base_url=http://localhost:8080" --reporters cli,junit --reporter-junit-export report_admin.xml
    
    - newman run "postman/Search & Filter Test.json" --env-var "base_url=http://localhost:8080" --reporters cli,junit --reporter-junit-export report_search.xml
    
    - newman run "postman/User Test.json" --env-var "base_url=http://localhost:8080" --reporters cli,junit --reporter-junit-export report_user.xml
    
    - newman run "postman/Cart Mechanic Test.json" --env-var "base_url=http://localhost:8080" --reporters cli,junit --reporter-junit-export report_cart.xml

    - newman run "postman/Cancell Test.json" --env-var "base_url=http://localhost:8080" --reporters cli,junit --reporter-junit-export report_cancel.xml

    - newman run "postman/Securite Test.json" --env-var "base_url=http://localhost:8080" --reporters cli,junit --reporter-junit-export report_security.xml

    - newman run "postman/EdgeCase.json" --env-var "baseUrl=http://localhost:8080" --reporters cli,junit --reporter-junit-export report_edge_case.xml

    - newman run "postman/Order Status & Security.json" --env-var "baseUrl=http://localhost:8080" --reporters cli,junit --reporter-junit-export report_order_status.xml

  artifacts:
    when: always
    reports:
      junit: report_*.xml